export default {
  backgroundName: 'Acolyte',
  traits: [
    'I idolize a particular hero of my faith, and constantly refer to that person\'s deeds and example.',
    'I can find common ground between the fiercest enemeies, empathizing with them and always working toward peace',
    'I see omens in every event and action. The gods try to speak to us, we just need to listen.',
    'Nothing can shake my optimistic attitude',
    'I quote (or misquote) sacred texts and proverbs in almost every situation',
    'I am tolerant (or intolerant) of other faiths and respect (or condemn) the worship of other gods',
    'I have enjoyed find food, drink, and high society among my temple\'s elite. Rough living grates on me.',
    'I have spent so long in the temple that I have little practical experience dealing with people in the outside world',
  ],
  ideals: [
    'Tradition. The ancient traditions of worship and sacrifice must be preseved and upheld',
    'Charity. I always try to help those in need, no matter what the personal cost.',
    'Change. We must help bring about the changes the gods are constantly working in the world.',
    'Power. I hope to one day rise to the top of my faith\'s religious hierarchy.',
    'Faith. I trust that my deity will guide my actions. I have faith that if I work hard, things will go well.',
    'Aspiration. I seek to prove myself worth of my god\'s favor by matching my actions against their teachings.',
  ],
  bonds: [
    'I would die to recover an ancient relic of my faith that was lost long ago.',
    'I will someday get revenge on the corrupt temple hierarchy who branded me a heretic.',
    'I owe my life to the priest who took me in when my parents died.',
    'Everything I do is for the common people.',
    'I will do anything to protect the temple where I served.',
    'I seek to preserve a sacred text that my enemies consider heretical and seek to destroy.',
  ],
  flaws: [
    'I judge others harshly, and myself even more severely',
    'I put too much trust in those who wield power within my temple\'s hierarchy.',
    'My piety sometimes leads me to blindly trust those that profess faith in my god.',
    'I am inflexible in my thinking.',
    'I am suspicious of strangers and expect the worst of them.',
    'Once I pick a goal, I become obsessed with it to the detriment of everything else in my life.',
  ],
  others: [],
  feature: {
    name: 'Shelter of the Faithful',
    description: 'You and your adventuring companions can expect to receive free healing and care at a temple, shrine, or other established presense of your faith, though you must provide any material components needed for spells. Those who share your religion will support you (but only you) at a modest lifestyle.',
  },
  proficiencies: {
    skills: ['Insight', 'Religion'],
    tools: [],
    languages: ['random', 'random'],
  },
  equipment: [
    'Holy symbol',
    'Prayer book',
    '5x Stick of incense',
    'Vestments',
    'Common clothes',
    'Pouch',
    '15 gp',
  ],
};
