export default {
  backgroundName: 'Charlatan',
  traits: [
    'I fall in and out of love easily and am always pursuing someone.',
    'I have a joke for every occasion, especially occasions where humor is inappropriate.',
    'Flattery is my preferred trick for getting what I want.',
    'I am a born gambler who can\'t resist taking a risk for a potential payoff.',
    'I lie about almost everything, even when there is no good reason to.',
    'Sarcasm and insults are my weapons of choice.',
    'I keep multiple holy symbols on me and invoke whatever deity might come in useful at any given moment.',
    'I pocket anything I see that might have some value',
  ],
  ideals: [
    'Independence. I am a free spirit—no one tells me what to do.',
    'Fariness. I never target people who can\'t afford to lose a few coins.',
    'Charity. I distribute the money I acquire to the people who really need it.',
    'Creativity. I never run the same con twice.',
    'Friendship. Material goods come and go. Bonds of friendship last forever.',
    'Aspiration. I am determined to make something of myself.',
  ],
  bonds: [
    'I fleeced the wrong person and must work to ensure that this individual never crosses paths with me or those I care about.',
    'I owe everything to my mentor—a horrible person who is probably rotting in jail somewhere',
    'Somewhere out there, I have a child who doesn\'t know me. I am making the world better for them.',
    'I come from a noble family, and one day I\'ll reclaim my lands and title from those who stole them from me.',
    'A powerful person killed someone I love. Some day soon, I will have my revenge.',
    'I swindled and ruined a person who didn\'t deserve it. I seek to atone for my misdeeds but might never be able to forgive myself.',
  ],
  flaws: [
    'I can\'t resist a pretty face.',
    'I\'m always in debt. I spend my ill-gotten gains on decadent luxuries faster than I bring them in.',
    'I am convinced that no one could ever fool me the way I fool others.',
    'I am too greedy for my own good. I can\'t resist taking a risk if there is money involved.',
    'I can\'t resist swindling people who are more powerful than me.',
    'I hate to admit it and will hate myself for it, but I\'ll run and preserve my own hide if the going gets tough',
  ],
  others: [
    [
      'Favorite Scheme: Cheating at games of chance.',
      'Favorite Scheme: Shaving coins.',
      'Favorite Scheme: Forging documents.',
      'Favorite Scheme: Insinuating myself into people\'s lives to prey on their weakness and secure their fortunes.',
      'Favorite Scheme: Identity theft.',
      'Favorite Scheme: Sleight-of-hand cons on street corners.',
      'Favorite Scheme: Convincing people that worthless junk is worth their hard-earned money',
    ],
  ],
  feature: {
    name: 'False Identity',
    description: 'You have created a second identity that includes documentation, established acquaintances, and disguises that allow you to assume that persona. Additionally, you can forge documents including official papers and personal letters, as long as you have seen an example of the kind of document or the handwriting you are trying to copy.',
  },
  proficiencies: {
    skills: ['Deception', 'Sleight of Hand'],
    tools: ['Disguise kit', 'Forgery kit'],
    languages: [],
  },
  equipment: [
    'Set of fine clothes',
    'Disguise kit',
    'Tools of the con of your choice',
    'Pouch',
    '15 gp',
  ],
};
