export default {
  className: 'Folk Hero',
  traits: [
    'I judge people by their actions, not their words.',
    'If someone is in trouble, I\'m always ready to lend help.',
    'When I set my mind to someonthing, I follow through no matter what gets in my way.',
    'I have a strong sense of fair play and always try to find the most equitable solution to arguments.',
    'I am confident in my own abilities and do what I can to instill confidence in others.',
    'Thinking is for other people. I prefer action.',
    'I misuse long words in an attempt to sound smarter.',
    'I get bored easily. When am I going to get on with my destiny?',
  ],
  ideals: [
    'Respect. People deserve to be treated with dignity and respect.',
    'Fairness. No one should get preferential treatment before the law, and no one is above the law.',
    'Freedom. Tyrants must not be allowed to oppress the people.',
    'Might. If I become strong. I can take what I want—what I deserve.',
    'Sincerity. There is no good in pretending to be something I\'m not.',
    'Destiny. Nothing and no one can steer me away from my higher calling.',
  ],
  bonds: [
    'I have a family, but I have no idea where they are. On e day, I hope to see them again.',
    'I worked the land, I love the land, and I will protect the land.',
    'A proud noble once gave me a horrible beating, and I will take my revenge on any bully I encounter.',
    'My tools are symbols of my past life, and I carry them so that I will never forget my roots.',
    'I protect those who cannot protect themselves.',
    'I wish my childhood sweetheart had come with me to pursue my destiny.',
  ],
  flaws: [
    'The tyrant who rules my land will stop at nothing to see me killed.',
    'I am convinced of the significance of my destiny, and blind to my shortcomings and the risk of failure.',
    'The people who knew me when I was young know my shameful secret, so I can never go home again.',
    'I have a weakness for the vices of the city, especially hard drink.',
    'Secretly, I believe that things would be better if I were a tyrant lording over the land.',
    'I have trouble trusting in my allies.',
  ],
  others: [
    [
      'Defining Event: I stood up to a tyrant\'s agents.',
      'Defining Event: I saved people during a natural disaster.',
      'Defining Event: I stood alone against a terrible monster.',
      'Defining Event: I stole from a corrupt merchant to help the poor.',
      'Defining Event: I led a militia to fight off an invading army.',
      'Defining Event: I broke into a tyrant\'s castle and stole weapons to arm the people.',
      'Defining Event: I trained the peasantry to use farm implements as weapons against a tyrant\'s soldiers.',
      'Defining Event: A lord rescinded an unpopular decree after I led a symbolic act of protest against it.',
      'Defining Event: A celestial or similar creature gave me a blessing.',
      'Defining Event: A celestial or similar creature revealed my secret origin.',
      'Defining Event: A fey or similar creature gave me a blessing.',
      'Defining Event: A fey or similar creature revealed my secret origin.',
      'Defining Event: Recruited into a lord\'s army, I rose to leadership and was commended for my heroism.',
    ],
  ],
  feature: {
    name: 'Rustic Hospitality',
    description: 'You fit in among the common folk with ease. You can find a place to hide, rest, or recuperate among other commoners, unless you have shown yourself to be a danger to them. They will sheild you from the law or anyone else searching for you, though they will not risk their lives for you.',
  },
  proficiencies: {
    skills: ['Animal Handling', 'Survival'],
    tools: ['artisans', 'Vehicles (land)'],
    languages: [],
  },
  equipment: [
    'artisans',
    'Shovel',
    'Iron pot',
    'Common clothes',
    'Pouch',
    '10 gp',
  ],
};
