export default {
  backgroundName: 'Guild Merchant',
  traits: [
    'I believe that anything worth doing is worth doing right. I can\'t help it—I\'m a perfectionist.',
    'I am a snob who looks down on those who cannot appreciate fine art.',
    'I always want to know how things work and what makes people tick.',
    'I\'m full of witty aphorisms and have a proverb ready for every occasion.',
    'I am rude to people who lack my commitment to hard work and fair play.',
    'I like to talk at length about my profession.',
    'I am well known for my work, and I want to make sure everyone appreciates it. I am always taken aback when people have not heard of me.',
  ],
  ideals: [
    'Community. It is the duty of all civilized people to strengthen the bonds of community and the security of civilization.',
    'Generosity. My talents were given to me so that I could use them to benefit the world.',
    'Freedom. Everyone should be free to pursue their own livelihood.',
    'Greed. I am only in it for the money.',
    'People. I am committed to the people I care about, not to ideals.',
    'Aspiration. I work hard to be the best there is at my craft.',
  ],
  bonds: [
    'The workshop where I leanred by trade is the most important place in the world to me.',
    'I created a great work for someone, and then found them unworthy to receive it. I am still looking for someone worthy.',
    'I owe my guild a great debt for forging me into the person I am today.',
    'I pursue wealth to secure someone\'s love.',
    'One day I will return to my guild and prove that I am the greatest artisan of them all.',
    'I will get revenge on the evil forces that destroyed my place of business and ruined my livelihood.',
  ],
  flaws: [
    'I will do anything to get my hands on something rare or priceless.',
    'I am quick to assume that someone is trying to cheat me.',
    'No one must ever learn that I once stole money from guild coffers',
    'I am never satisfied with what I have—I always want more.',
    'I would kill to acquire a noble title.',
    'I am horribly jealous of anyong who can outshine my handiwork. Everywhere I go, I am surrounded by rivals.',
  ],
  others: [
    [
      'Guild: Alchemists and Apothecaries.',
      'Guild: Armorers, Locksmiths, and Firesmiths.',
      'Guild: Brewers, Distillers, and Vintners.',
      'Guild: Calligraphers, Scribes, and Scriveners.',
      'Guild: Carpenters, Roofers, and Plasterers.',
      'Guild: Cartographers, Surveryors, and Chart-makers.',
      'Guild: Cobblers and Shoemakers.',
      'Guild: Cooks and Bakers.',
      'Guild: Glassblowers and Glaziers.',
      'Guild: Jewelers and Gemcutters.',
      'Guild: Leatherworks, Skinners, and Tanners.',
      'Guild: Masons and Stonecutters.',
      'Guild: Painters, Limners, and Sign-makers.',
      'Guild: Potters and Tile-makers.',
      'Guild: Shipwrights and Sailmakers.',
      'Guild: Smiths and Metal-forgers.',
      'Guild: Tinkers, Pewterers, and Casters.',
      'Guild: Wagon-makers and Cartwrights.',
      'Guild: Weavers and Dyers.',
      'Guild: Woodcarvers, Coopers, and Bowyers.',
    ],
    [
      'Guild Merchant: You belong to a guild of traders, caravan master, or shopkeepers. You don\'t craft items yourself but earn a living by buying and selling the works of others (or the raw materials artisans need to practice their craft). Your guild might be a large merchant consortium or family with interests across the region.',
    ],
  ],
  feature: {
    name: 'Guild Membership',
    description: 'Your fellow guild members will provide you with lodging and food if necessary, and pay for your funeral if needed. If you are accused of a crime, your guild will support you if a good case can be made for your innocense or the crime is justifiable. You can also gain access to powerful polical figures through the guild, if you are a member in good standing. SUch connection might require the donation of money or magic itme to the guild\'s coffers. You must pay dues of 5 gp per month to the guild. If you miss payments, you must make up back dues to remain in good standing.',
  },
  proficiencies: {
    skills: ['Insight', 'Persuasion'],
    tools: ['Navigator\'s tools'],
    languages: ['random'],
  },
  equipment: [
    'Mule',
    'Cart',
    'Letter of introduction from your guild',
    'Set of traveler\'s clothes',
    'Pouch',
    '15 gp',
  ],
};
