export default {
  backgroundName: 'Hermit',
  traits: [
    'I have been isolated for so long that I rarely speak, preferring gestures and the occasional grunt.',
    'I am utterly serene, even in the face of disaster.',
    'The leader of my community had something wise to say on every topic, and I am eager to share their wisdom.',
    'I feel tremendous empathy for all who suffer.',
    'I am oblivious to etiquette and social expectations.',
    'I connect everything that happens to me to a grand, cosmic plan.',
    'I often get lost in my own thoughts and contemplation, becoming oblivious to my own surroundings.',
    'I am working on a grand philosophical theory and love sharing my ideas.',
  ],
  ideals: [
    'Greater Good. My gifts are meant to e shared with all, not used for my own benefit.',
    'Logic. Emotions must not cloud our sense of what is right and true, or our logial thinking.',
    'Free Thinking. Inquiry and curiousity are the pillars of progress.',
    'Power. Solitude and contemplation are paths toward mystical or magical power.',
    'Live and Let Live. Meddling in the affairs of others only causes trouble.',
    'Self-Knowledge. If you know yourself, there is nothing left to know.',
  ],
  bonds: [
    'Nothing is more important than the other members of my hermitage.',
    'Nothing is more important than the other members of my order.',
    'Nothing is more important than the other members of my association.',
    'I entered seclusion to hide from the ones who might still be hunting me. I must someday confront them.',
    'I am still seeking the enlightenment I pursued in my seclusion, and it still eludes me.',
    'I entered seclusion because I loved someone I could not have.',
    'Should my discovery come to light, it could bring ruin to the world.',
    'My isolation gave me great insight into a great evil that only I can destroy.',
  ],
  flaws: [
    'Now that I have returned to the world, I enjoy its delights a little too much.',
    'I harbor dark, bloodthirsty thoughts that my isolation and meditation failed to quell.',
    'I am dogmatic in my thoughts and philosophy.',
    'I let my need to win arguments overshadow friendships and harmony.',
    'I would risk too much to uncover a lost bit of knowledge.',
    'I like keeping secrets and won\'t share them with anyone.',
  ],
  others: [
    [
      'Reason for Seclusion: I was searching for spritual enlightenment.',
      'Reason for Seclusion: I was partaking of communal living in accordance with the dictates of a religious order.',
      'Reason for Seclusion: I was exiled for a crime I did not commit.',
      'Reason for Seclusion: I retreated from society after a life-altering event.',
      'Reason for Seclusion: I needed a quiet place to work on my art.',
      'Reason for Seclusion: I needed a quiet place to work on my literature.',
      'Reason for Seclusion: I needed a quiet place to work on my music.',
      'Reason for Seclusion: I needed a quiet place to work on my manifesto.',
      'Reason for Seclusion: I needed to commune with nature, far from civilization.',
      'Reason for Seclusion: I was the caretaker of an ancient ruin or relic.',
      'Reason for Seclusion: I was a pilgrim in search of a person of spiritual significance.',
      'Reason for Seclusion: I was a pilgrim in search of a place of spiritual significance.',
      'Reason for Seclusion: I was a pilgrim in search of a relic of spiritual significance.',
    ],
  ],
  feature: {
    name: 'Discovery',
    description: 'The quiet seclusion of your extended hermitage gave you access to a unique and powerful discovery. The exact nature of this revelation depends on the nature of your seclusion. Work with your DM to determine the details of your discovery and its impact on the campaign.',
  },
  proficiencies: {
    skills: ['Medicine', 'Religion'],
    tools: ['Herbalism kit'],
    languages: ['random'],
  },
  equipment: [
    'Scroll case stuffed full of your notes/studies/prayers',
    'Winter blanket',
    'Common clothes',
    'Herbalism kit',
    '5 gp',
  ],
};
