export default {
  backgroundName: 'Knight',
  traits: [
    'My eloquent flattery makes everyone I talk to feel like the most wonderful and important person in the world.',
    'The common folk love me for my kindness and generosity.',
    'No one could doubt by looking at my regal bearing that I am a cut above the unwashed masses.',
    'I take great pains to always look my best and follow the latest fashions.',
    'I do not like to get my hands dirty, and I won\'t be caught dead in unsuitable acommodations.',
    'Despite my noble birth, I do not place myself above other folk. We all have the same blood.',
    'My favor, once lost, is gone forever.',
    'If you do me an injury, I will crush you, ruin your name, and salt your fields.',
  ],
  ideals: [
    'Respect. Respect is due to me beause of my position, but all people regardless of station deserve to be treated with dignity.',
    'Responsibility. It is my duty to respect the authority of those above me, just as those below me must respect mine.',
    'Independence. I must prove that I can handle myself without the coddling of my family.',
    'Power. If I can attain more power, no one will tell me what to do.',
    'Family. Blood runs thicker than water.',
    'Noblesse Oblige. It is my duty to protect and care for the people beneath me.',
  ],
  bonds: [
    'I will face any challenge to win the approval of my family.',
    'My house\'s alliannce with another noble family must be sustained at all costs.',
    'Nothing is more important than the other members of my family.',
    'I am in love with the heir of a family that my family despises.',
    'My loyalty to my sovereign is unwavering.',
    'The common folk must see me as a hero of the people.',
  ],
  flaws: [
    'I secretly believe that everyone is beneath me.',
    'I hide a truly scandalous secret that could ruin my family forever.',
    'I too often hear veiled insults and threats in every word addressed to me, and I am quick to anger about it.',
    'I have an insatiable desire for carnal pleasures.',
    'In fact, the wold does revolve around me.',
    'By my words and actions, I often bring shame to my family.',
  ],
  others: [],
  feature: {
    name: 'Retainers',
    description: 'You have the service of three retainers loyal to your family. These retainers can be attendants or messengers, and one might be a majordomo. Your retainers are commoners who can perform mundane tasks for you, but they do not fight for you, will not follow you into obviously dangerous areas (such as dungeons), and will leave if they are frequently endangered or abused.',
  },
  proficiencies: {
    skills: ['History', 'Persuasion'],
    tools: ['gaming'],
    languages: ['random'],
  },
  equipment: [
    'Fine clothes',
    'Signet ring',
    'Scroll of pedigree',
    'Purse',
    '25 gp',
  ],
};
