export default {
  backgroundName: 'Outlander',
  traits: [
    'I am driven by a wanderlust that led me away from home.',
    'I watch over my friends as if they were a litter of newborn pups.',
    'I once ran twenty-five miles without stopping to warn my clan of an approaching moblin horde. I would do it again if I had to.',
    'I have a lesson for every situation, drawn from observing nature.',
    'I place no stock in wealthy or well-mannered folk. Money and manners won\'t save you from a hungry owlbear.',
    'I am always picking things up, absently fiddling with them, and sometimes accidentally breaking them.',
    'I feel far more comfortable around animals than people.',
    'I was, in fact, raised by wolves.',
  ],
  ideals: [
    'Change. Life is like the seasons, in constant change, and we must change with it.',
    'Greater Good. It is each person\'s responsibility to make the most happiness for the whole tribe.',
    'Honor. If I dishonor myself, I dishonor my whole clan.',
    'Might. The strongest are meant to rule.',
    'Nature. The natural world is more important than all the constructs of civilization.',
    'Glory. I must earn glory in battle, for myself and my clan.',
  ],
  bonds: [
    'My family is the most important thing in my life, even when they are far from me.',
    'My clan is the most important thing in my life, even when they are far from me.',
    'My tribe is the most important thing in my life, even when they are far from me.',
    'An injury to the unspoiled wilderness of my home is an injury to me.',
    'I will bring terrible wrath down on the evildoers who destoryed my homeland.',
    'I am the last of my tribe, and it is up to me to ensure their names enter legend.',
    'I suffer awful visions of a coming disaster and will do anything to prevent it.',
    'It is my duty to provide children to sustain my tribe.',
  ],
  flaws: [
    'I am too enamored of ale, wine, and other intoxicants.',
    'There\'s no room for caution in a life lived to the fullest.',
    'I remember every insult I\'ve received and nurse a silent resentment toward anyone who\'s ever wronged me.',
    'I am slow to trust members of other races, tribes, and societies.',
    'Violence is my answer to almost any challenge.',
    'Do not expect me to save those who can\'t save themselves. It is nature\'s way that the strong thrive and the weak perish.',
  ],
  others: [
    [
      'Origin: Forester',
      'Origin: Trapper',
      'Origin: Homesteader',
      'Origin: Guide',
      'Origin: Exile',
      'Origin: Outcast',
      'Origin: Bounty hunter',
      'Origin: Pilgrim',
      'Origin: Tribal nomad',
      'Origin: Hunter-gatherer',
      'Origin: Tribal marauder',
    ],
  ],
  feature: {
    name: 'Wanderer',
    description: 'You have an excellent memory for maps and geogrpahy, and you can always recall the general layout of terrain, settlements, and other features around you. In addition, you can find food and fresh water for yourself and up to five other people each day, provided that the land offers berries, small game, water, and so forth.',
  },
  proficiencies: {
    skills: ['Athletics', 'Survival'],
    tools: ['instrument'],
    languages: ['random'],
  },
  equipment: [
    'Staff',
    'Hunting trap',
    'Trophy from a kill',
    'Traveler\'s clothes',
    'Pouch',
    '10 gp',
  ],
};
