export default {
  backgroundName: 'Sage',
  traits: [
    'I use polysyllablic words that convey the impression of great erudition.',
    'I have read every book in the world\'s greatest libraries—or I like to boast that I have.',
    'I am used to helping out those who are not as smart as I am, and I patiently explain anything and everything to others.',
    'There is nothing I like more than a good mystery.',
    'I am willing to listen to every side of an argument before I make my own judgments.',
    'I... speak... slowly... when talking... to idiots... which... almost... everyone is... compared... to me...',
    'I am horribly, horribly awkward in social situations.',
    'I am convinced that people are always trying to steal my secrets.',
  ],
  ideals: [
    'Knowledge. The path to power and self-improvement is through knowledge.',
    'Beauty. What is beautiful points us beyond itself toward what is true.',
    'Logic. Emotions must not cloud our lgoical thinking.',
    'No Limits. Nothing should fetter the infinite possibility inherent in all existence.',
    'Power. Knowledge is the path to power and domination.',
    'Self-Improvement. The goal of a life of study is the betterment of oneself.',
  ],
  bonds: [
    'It is my duty to protect my students.',
    'I have an ancient text that holds terrible secrets that must not fall into the wrong hands.',
    'I work to preserve a library.',
    'I work to preserve a university.',
    'I work to preserve a scriptorium.',
    'I work to preserve a monastery.',
    'My life\'s work is a series of tomes related to a specific field of lore.',
    'I have been searching my whole life fro the answer to a certain question.',
    'I sold my soul for knowledge. I hope to do great deeds and win it back.',
  ],
  flaws: [
    'I am easily distracted by the promise of information.',
    'Most people scream and run when they see a demon. I stop and take notes on its anatomy.',
    'Unlocking an ancient mystery is worth the price of a civilization.',
    'I overlook obvious solutions in favor of complicated ones.',
    'I speak without really thinking through my words, invariably insulting others.',
    'I can\'t keep a secret to save my life, or anyone else\'s.',
  ],
  others: [
    [
      'Specialty: Alchemist',
      'Specialty: Astronomer',
      'Specialty: Discredited academic',
      'Specialty: Librarian',
      'Specialty: Professor',
      'Specialty: Researcher',
      'Specialty: Wizard\'s apprentice',
      'Specialty: Scribe',
    ],
  ],
  feature: {
    name: 'Researcher',
    description: 'When you attempt to learn or recall a piece of lore, if you do not know that information, you often know where and from whom you can obtain it. Usually, this information comes from a library, scriptorium, university, or a sage or other learned person or creature. Your DM might rule that the knowledge you seek is secreted away in an almost inaccessible place, or that it simply cannot be found.',
  },
  proficiencies: {
    skills: ['Arcana', 'History'],
    tools: [],
    languages: ['random', 'random'],
  },
  equipment: [
    'Bottle of ink',
    'Quill',
    'Small knife',
    'Letter from a dead colleague posing a question you have not yet been able to answer',
    'Common clothes',
    'Pouch',
    '10 gp',
  ],
};
