export default {
  backgroundName: 'Soldier',
  traits: [
    'I am always polite and respectful.',
    'I am haunted by memories of war. I can\'t get the images of violence of out my mind.',
    'I have lost too many friends, and I am slow to make new ones.',
    'I am full of inspiring and cautionary tales from my military experience relevant to almost every combat situation.',
    'I can stare down a hell hound without flinching.',
    'I  enjoy being strong and like breaking things.',
    'I have a crude sense of humor.',
    'I face problems head-on. A simple, direct solution is the best path to success.',
  ],
  ideals: [
    'Greater Good. Our lot is to lay down our lives in defense of others.',
    'Responsibility. I do what I must and obey just authority.',
    'Independence. When people follow orders blindly, they embrace a kind of tyranny.',
    'Might. In life as in war, the stronger force wins.',
    'Live and Let Live. Ideals aren\'t worth killing over or going to war for.',
    'Nation. My city, nation, or people are all that matter.',
  ],
  bonds: [
    'I would still lay down my life for the people I served with.',
    'Someone saved my life on the battlefield. To this day, I will never leave a friend behind.',
    'My honor is my life.',
    'I will never forget the crushing defeat my company suffered or the enemies who dealt it.',
    'Those who fight beside me are those worth dying for.',
    'I fight for those who cannot fight for themselves.',
  ],
  flaws: [
    'The monstrous enemy we faced in battle still leaves me quivering with fear.',
    'I have little respect for anyone who is not a proven warrior.',
    'I made a terrible mistake in battle that cost many lives.',
    'My hatred of my enemies is blind and unreasoning.',
    'I obey the law, even if the law causes misery.',
    'I would rather eat my armor than admit when I\'m wrong.',
  ],
  others: [
    [
      'Specialty: Officer',
      'Specialty: Scout',
      'Specialty: Infantry',
      'Specialty: Cavalry',
      'Specialty: Medic',
      'Specialty: Quartermaster',
      'Specialty: Standard bearer',
      'Specialty: Support staff',
    ],
  ],
  feature: {
    name: 'Military Rank',
    description: 'You have a military rank from your career as a soldier. Soldiers loyal to your former military organization still recognize your authority and influence, and they defer to you if they are of a lower rank. You can invoke your rank to exert influene over other soldiers and requisition simple equipment or horses for temporary use. You can also usually gain access to friendly military encampments and fortresses where your rank is recognized.',
  },
  proficiencies: {
    skills: ['Athletics', 'Intimidation'],
    tools: ['gaming', 'Vehicles (land)'],
    languages: [],
  },
  equipment: [
    'Insignia of rank',
    'Trophy taken from fallen enemy',
    'gaming',
    'Common clothes',
    'Pouch',
    '10 gp',
  ],
};
