export default {
  backgroundName: 'Urchin',
  traits: [
    'I hide scraps of food and trinkets away in my pockets.',
    'I ask a lot of questions.',
    'I like to squeeze into small places where no one else can get to me.',
    'I sleep with my back to a wall or tree, with everything I own wrapped up in a bundle in my arms.',
    'I eat like a pig and have bad manners.',
    'I think anyone who is nice to me is hiding evil intent.',
    'I don\'t like to bathe.',
    'I bluntly say what other people are hinting at or hiding.',
  ],
  ideals: [
    'Respect. All people, rich or poor, deserve respect.',
    'Community. We have to take care of each other, because no one else is going to do it.',
    'Change. The low are lifted up, and the high and mighty are brought down. Change is the nature of things.',
    'Retribution. The rich need to be shown what life and death are like in the gutters.',
    'People. I help the people who help me—that\'s what keeps us alive.',
    'Aspiration. I am going to prove that I\'m worthy of a better life.',
  ],
  bonds: [
    'My town or city is my home, and I\'ll fight to defend it.',
    'I sponsor an orphanage to keep others from enduring what I was forced to endure.',
    'I owe my survival to another urchin who taught me to live on the streets.',
    'I owe a debt I can never repay to the person who took pity on me.',
    'I escaped my life of poverty by robbing an important person, and I\'m wanted for it.',
    'No one else should have to endure the hardships I\'ve been through.',
  ],
  flaws: [
    'If I am outnumbered, I will run from a fight.',
    'Gold seems like a lot of money to me, and I will do just about anything for more of it.',
    'I will never fully trust anyone other than myself.',
    'I would rather kill someone in their sleep than fight fair.',
    'It\'s not stealing if I need it more than someone else.',
    'People who can\'t take care of themselves get what they deserve.',
  ],
  others: [],
  feature: {
    name: 'City Secrets',
    description: 'When you are not in combat, you and companions you lead can travel between any two locations in the city twice as fast as your speed would normally allow.',
  },
  proficiencies: {
    skills: ['Sleight of Hand', 'Stealth'],
    tools: ['Disguise kit', 'Thieves\'s tools'],
    languages: [],
  },
  equipment: [
    'Small knife',
    'Map of the city you grew up in',
    'Pet mouse',
    'Token to remember your parents by',
    'Common clothes',
    'Pouch',
    '10 gp',
  ],
};
