const cantrips = [
  'Control Flames (XGtE)',
  'Create Bonfire (XGtE)',
  'Druidcraft',
  'Frostbite (XGtE)',
  'Guidance',
  'Gust (XGtE)',
  'Infestation (XGtE)',
  'Magic Stone (XGtE)',
  'Mending',
  'Mold Earth (XGtE)',
  'Poison Spray',
  'Primal Savagery (XGtE)',
  'Produce Flame',
  'Resistance',
  'Shape Water (XGtE)',
  'Shillelagh',
  'Thorn Whip',
  'Thunderclap (XGtE)',
];

const firstLevel = [
  'Absorb Elements (XGtE)',
  'Animal Friendship',
  'Beast Bond (XGtE)',
  'Charm Person',
  'Create or Destroy Water',
  'Cure Wounds',
  'Detect Magic ®',
  'Detect Poison and Disease ®',
  'Earth Tremor (XGtE)',
  'Entangle',
  'Faerie Fire',
  'Fog Cloud',
  'Goodberry',
  'Healing Word',
  'Ice Knife (XGtE)',
  'Jump',
  'Longstrider',
  'Purify Food and Drink ®',
  'Speak with Animals ®',
  'Snare (XGtE)',
  'Thunderwave',
];

export default {
  cantrips,
  firstLevel,
};
