const cantrips = [
  'Acid Splash',
  'Blade Ward',
  'Chill Touch',
  'Control Flames (XGtE)',
  'Create Bonfire (XGtE)',
  'Dancing Lights',
  'Fire Bolt',
  'Friends',
  'Frostbite (XGtE)',
  'Gust (XGtE)',
  'Infestation (XGtE)',
  'Light',
  'Mage Hand',
  'Mending',
  'Message',
  'Minor Illusion',
  'Mold Earth (XGtE)',
  'Poison Spray',
  'Prestidigitation',
  'Ray of Frost',
  'Shape Water (XGtE)',
  'Shocking Grasp',
  'True Strike',
  'Thunderclap (XGtE)',
];

const firstLevel = [
  'Absorb Elements (XGtE)',
  'Burning Hands',
  'Catapult (XGtE)',
  'Chaos Bolt (XGtE)',
  'Charm Person',
  'Chromatic Orb',
  'Color Spray',
  'Comprehend Languages',
  'Detect Magic',
  'Disguise Self',
  'Earth Tremor (XGtE)',
  'Expeditious Retreat',
  'False Life',
  'Feather Fall',
  'Fog Cloud',
  'Ice Knife (XGtE)',
  'Jump',
  'Mage Armor',
  'Magic Missile',
  'Ray of Sickness',
  'Shield',
  'Silent Image',
  'Sleep',
  'Thunderwave',
  'Witchbolt',
];

export default {
  cantrips,
  firstLevel,
};
