const cantrips = [
  'Acid Splash',
  'Blade Ward',
  'Chill Touch',
  'Control Flames (XGtE)',
  'Create Bonfire (XGtE)',
  'Dancing Lights',
  'Fire Bolt',
  'Friends',
  'Frostbite (XGtE)',
  'Gust (XGtE)',
  'Infestation (XGtE)',
  'Light',
  'Mage Hand',
  'Mending',
  'Message',
  'Minor Illusion',
  'Mold Earth (XGtE)',
  'Poison Spray',
  'Prestidigitation',
  'Ray of Frost',
  'Shape Water (XGtE)',
  'Shocking Grasp',
  'True Strike',
  'Thunderclap (XGtE)',
  'Toll the Dead (XGtE)',
];

const firstLevel = [
  'Absorb Elements (XGtE)',
  'Alarm ®',
  'Burning Hands',
  'Catapult (XGtE)',
  'Cause Fear (XGtE)',
  'Charm Person',
  'Chromatic Orb',
  'Color Spray',
  'Comprehend Languages ®',
  'Detect Magic ®',
  'Disguise Self',
  'Earth Tremor (XGtE)',
  'Expeditious Retreat',
  'False Life',
  'Feather Fall',
  'Find Familiar ®',
  'Fog Cloud',
  'Grease',
  'Ice Knife (XGtE)',
  'Identify ®',
  'Illusory Script ®',
  'Jump',
  'Longstrider',
  'Mage Armor',
  'Magic Missile',
  'Protection from Evil and Good',
  'Ray of Sickness',
  'Shield',
  'Silent Image',
  'Sleep',
  'Snare (XGtE)',
  'Tasha\'s Hideous Laughter',
  'Tenser\'s Floating Disk ®',
  'Thunderwave',
  'Unseen Servant ®',
  'Witchbolt',
];

export default {
  cantrips,
  firstLevel,
};
