const cantrips = [
  'Acid Splash',
  'Blade Ward',
  'Chill Touch',
  'Dancing Lights',
  'Fire Bolt',
  'Friends',
  'Light',
  'Mage Hand',
  'Mending',
  'Message',
  'Minor Illusion',
  'Poison Spray',
  'Prestidigitation',
  'Ray of Frost',
  'Shocking Grasp',
  'True Strike',
];

const firstLevel = [
  'Alarm ®',
  'Burning Hands',
  'Charm Person',
  'Chromatic Orb',
  'Color Spray',
  'Comprehend Languages ®',
  'Detect Magic ®',
  'Disguise Self',
  'Expeditious Retreat',
  'False Life',
  'Feather Fall',
  'Find Familiar ®',
  'Fog Cloud',
  'Grease',
  'Identify ®',
  'Illusory Script ®',
  'Jump',
  'Longstrider',
  'Mage Armor',
  'Magic Missile',
  'Protection from Evil and Good',
  'Ray of Sickness',
  'Shield',
  'Silent Image',
  'Sleep',
  'Tasha\'s Hideous Laughter',
  'Tenser\'s Floating Disk ®',
  'Thunderwave',
  'Unseen Servant ®',
  'Witchbolt',
];

export default {
  cantrips,
  firstLevel,
};
